name: ML Workflow CI

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install MLflow
      run: pip install "mlflow>=2.22.0"

    - name: Run MLProject
      id: run_mlflow
      run: |
        cd MLProject
        mlflow run . --env-manager=local
        MODEL_PATH=$(dirname $(find mlruns -name "MLmodel" | head -n 1))
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
        echo "Model Path: $MODEL_PATH"

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/${{ env.MODEL_PATH }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        cd MLProject
        # Build image using mlflow
        mlflow models build-docker -m ${{ env.MODEL_PATH }} -n ${{ secrets.DOCKERHUB_USERNAME }}/ml-model-dicoding:latest
        
        # Push the image
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model-dicoding:latest
